<?php

if (!class_exists('modxYMLprice')) {
    require_once dirname(__FILE__, 2) . '/model/modxYMLprice/modxYMLprice.php';
}

/**
 * @property object|null $modxYMLprice
 */
class ModxYMLpriceIndexManagerController extends modParsedManagerController
{

    /** @var modxYMLprice $modxYMLprice */
    public $modxYMLprice;
    /** @var miniShop2 $miniShop2 */
    public $miniShop2;



    public function initialize() {

        $this->modxYMLprice = $this->modx->getService('modxYMLprice', 'modxYMLprice');
        $configYml = json_encode($this->modxYMLprice->config);

        // Let's check the HTTP method to display a different content based on it (ie. when we submit a form)
        $this->method = filter_input(INPUT_SERVER, 'REQUEST_METHOD');
        // Some hack to put the HTML content in its right place so ExtJS can resize the main content "area" properly
        $this->addHtml("
            <script>
            var modxYMLpriced = $configYml;
            Ext.onReady(function() {

                var node = document.getElementById('modx-panel-holder').nextElementSibling
                    ,content = node.innerHTML;
                node.parentNode.removeChild(node);
                MODx.add({
                    xtype: 'box'
                    ,html: content
                    ,cls: node.className || ''
                    ,id: node.id || Ext.id()
                });
            });
            </script>
            ");
    }


    public function getPageTitle()
    {
        return 'modxYMLprice - settings';
    }

    public function process(array $scriptProperties = [])
    {

        return '[[$chunk-name]]';
    }

    public function loadCustomCssJs()
    {

        $this->addCss(MODX_ASSETS_URL.'components/modxYMLprice/css/modxYMLprice.css' . '?_=' . time());
        //$this->addLastJavascript(MODX_ASSETS_URL.$configFile . '?_=' . time());
        $this->addLastJavascript(MODX_ASSETS_URL . 'components/modxYMLprice/js/mgr/modxYMLprice.js?_=' . time());
        parent::loadCustomCssJs(); // TODO: Change the autogenerated stub
    }

    public function getTemplateFile()
    {

        return MODX_ASSETS_PATH . 'components/modxYMLprice/templates/mgr/main.tpl';
        // TODO: Change the autogenerated stub
    }

}
